services:
  # Base de données MongoDB
  mongodb:
    image: mongo:latest
    container_name: med_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - med_network

  # Script Python d'automatisation de la migration
  migration_script:
    build: .
    container_name: med_migration_container
    depends_on:
      - mongodb
    networks:
      - med_network

volumes:
  mongo_data:

networks:
  med_network:
    driver: bridge