services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # ICI : On transmet explicitement les variables pour le fichier init-mongo.js
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - healthcare_network
    command: mongod --auth

  migration_script:
    build: .
    container_name: migration_container
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data
    networks:
      - healthcare_network

volumes:
  mongo_data:

networks:
  healthcare_network:
    driver: bridge